// <auto-generated />
using System;
using IntensApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntensApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019170116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntensApp.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "061222333",
                            DateOfBirth = new DateTime(2000, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david@gmail.com",
                            FullName = "David Stepanic"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "069222333",
                            DateOfBirth = new DateTime(1992, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "milos@gmail.com",
                            FullName = "Milos Obilic"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "061999333",
                            DateOfBirth = new DateTime(1380, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lazar@gmail.com",
                            FullName = "Lazar Hrebeljanovic"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "069222555",
                            DateOfBirth = new DateTime(1856, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nikola@gmail.com",
                            FullName = "Nikola Tesla"
                        });
                });

            modelBuilder.Entity("IntensApp.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 6
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 5
                        });
                });

            modelBuilder.Entity("IntensApp.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java Programming"
                        },
                        new
                        {
                            Id = 3,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Golang"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rust"
                        });
                });

            modelBuilder.Entity("IntensApp.Models.CandidateSkill", b =>
                {
                    b.HasOne("IntensApp.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntensApp.Models.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("IntensApp.Models.Candidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("IntensApp.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
